
[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.5"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.4.0"

[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  version = "1.1.0"

[[constraint]]
  name = "github.com/docker/docker/client"
  version = "1.13.0"

[[constraint]]
  name = "github.com/docker/go-connections"
  version = "0.4.0"

[prune]
  go-tests = true
  unused-packages = true
