import * as DROPin from "dropin-recipes"

/*
   ____  ____   ___  ____  _ _
  |  _ \|  _ \ / _ \|  _ \( |_)_ __
  | | | | |_) | | | | |_) |/| | '_ \
  | |_| |  _ <| |_| |  __/  | | | | |
  |____/|_| \_\\___/|_|     |_|_| |_|

  This file was automatically generated by the DROP'in CLI
  Use it instead to update its content, the file will be overwritten
*/

export interface Repository {
  host: string
  owner: string
  name: string
  slug?: string
}

export interface Workspace {
  name: string
  slug: string
  version: number
  repositories: Repository[]
}

export class Workspaces {

  static getOne(filters: string): Promise<DROPin.Line<Workspace>> {
    return DROPin.Request.getOneLine<Workspace>("KiwiBundle", "workspaces", { filters })
  }

}
